version: "1.1"

on:
  push:
    branches:
      - master

stages:
  - stage:
      - git-checkout:
          version: "1.0"
  - stage:
      - extract-repo-version:
          params:
            git_dir: ${{ dirs.git-checkout }}
  - stage:
      - js:
          version: "1.0"
          params:
            workdir: ${{ dirs.git-checkout }}
            dependency_cmd: npm i
            build_cmd: npm run build
            dest_dir: ./dest
            container_type: spa
          resources:
            cpu: 1
            mem: 4096
          caches:
            - path: ${{ dirs.git-checkout }}/node_modules
  - stage:
      - custom-script:
          alias: trans
          commands:
            - echo "FROM ${{ outputs.js.image }}" > Dockerfile
  - stage:
      - dockerfile:
          alias: build-image
          params:
            workdir: ${{ dirs.trans }}
            path: ${{ dirs.trans }}/Dockerfile
            registry:
              password: ${{ configs.docker_registry_password }}
              url: ${{ configs.docker_registry }}
              username: ${{ configs.docker_registry_username }}
            image:
              name: docs
              tag: ${{ outputs.extract-repo-version.image_tag }}
  - stage:
      - release:
          params:
            tag_version: ${{ outputs.extract-repo-version.version }}
            dice_yml: ${{ dirs.git-checkout }}/dice.yml
            image:
              doc: ${{ outputs.build-image.image }}
  - stage:
      - dice:
          params:
            release_name: ${{ outputs.extract-repo-version.version }}
            workspace: TEST
            application_name: docs
            type: application
